name: build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false

    - name: Build package
      run: poetry build

    - name: Setup testing dependencies
      run: |
        pip install dist/belgian_deduce-*.whl
        poetry install --only dev --no-root

    - name: Test build
      run: python -m pytest .

    - name: Upload distribution artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish:

    name: Publish package to PyPI
    needs:
    - build
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/belgian-deduce
    permissions:
      id-token: write

    steps:
    - name: Download distribution artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
